name: Build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: List images
        run: sdkmanager --channel=0 "system-images;android-30;aosp_atd;x86_64"

      - name: Run instrumented tests with GMD
        run: ./gradlew cleanManagedDevices --unused-only &&
          ./gradlew nexusOneapi30aosp_atdDebugAndroidTest
          -Pandroid.testoptions.manageddevices.emulator.gpu="swiftshader_indirect"
          -Pandroid.experimental.testOptions.managedDevices.maxConcurrentDevices=1
          -Pandroid.experimental.testOptions.managedDevices.setupTimeoutMinutes=180
